### ISSUE TITLE
default options / default login in windows

### ISSUE THREAD

**Issue by jdthorpe** [rstats-db/RMySQL#102]
First, the description of the `default.file` argumnet of the `dbConnect` in `RMySQL/R/connect.R`
only applies to Unix-like OS's:

```
#' @param default.file string of the file name with MySQL client options.
#'   Defaults to \code{\$HOME/.my.cnf}
```

The locations of the options files in windows are described [here](https://dev.mysql.com/doc/refman/5.7/en/option-files.html) and can also be found in these lines which appear about half way through the output returned by calling `% mysql --help`:

```
Default options are read from the following files in the given order:
C:\Windows\my.ini C:\Windows\my.cnf C:\my.ini C:\my.cnf C:\Program Files\MySQL\my.ini C:\Program Files\MySQL\my.cnf
```

Second, in windows, the only way to have default connection settings with MySQL 
that aren't shared with all users of your computer is to use the [mysql_config_editor](https://dev.mysql.com/doc/refman/5.7/en/mysql-config-editor.html)
and create a set of (encrypted) login credentials.  This works beautifully from the command line
(via `c:\> mysql`), but does not seem to work with RMySQL: calling `dbConnect(RMySQL::MySQL(),groups="client")` raises an error.   For example, on my machine, I get: 

```
> con_sql <- dbConnect(MySQL())
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Access denied for user 'User Name'@'localhost' (using password: NO)
> con_sql <- dbConnect(MySQL(),default.file=path.expand("~/.my.cnf"))
> DBI::dbGetQuery(con_sql,"SELECT NOW()")
                NOW()
1 2015-11-07 00:11:14
```

One can of course specify  `dbConnect(... , default.file=path.expand("~/.my.cnf"))` to explicitly reference a saved `.my.cnf` file, but it would be great if RMySQL could use the same defaults as the `mysql` command line client.  In the worst case, perhaps `default.file` could default to `getOption("default.file")`.

Also, In case it's useful, here's my info:

```
> packageVersion("RMySQL")
[1] ‘0.10.5’
> R.Version()
$platform
[1] "x86_64-w64-mingw32"
$arch
[1] "x86_64"
$os
[1] "mingw32"
$system
[1] "x86_64, mingw32"
$status
[1] ""
$major
[1] "3"
$minor
[1] "2.2"
$year
[1] "2015"
$month
[1] "08"
$day
[1] "14"
$`svn rev`
[1] "69053"
$language
[1] "R"
$version.string
[1] "R version 3.2.2 (2015-08-14)"
$nickname
[1] "Fire Safety"
```

**Comment by krlmlr** [comment]
Is this about using `.mylogin.cnf` by default, even before `.my.cnf`?

**Comment by jdthorpe** [comment]
The second issue is about being able to use an options file in windows that isn't available to all users on the machine (at my work, other individuals may use this machine).  In windows, MySQL only references the `.cnf` and `.ini` options files in `c:\`, `c:\program files` and `c:\windows`, which are available anyone who uses this workstation.  

MySQL will reference the stored `.mylogin.cnf` file from the command line, but not via `RMySQL`.  

Also, the first (and minor) issue is that the documentation is just plain wrong for windows users.

**Comment by krlmlr** [comment]
NB: `dbConnect(MySQL(), groups = "mysql")` accesses the information stored in `.mylogin.cnf` on my Ubuntu 15.10 system. Can you please confirm?

I'd be happy to review a PR that fixes the documentation problems.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
