### ISSUE TITLE
Commands not supported in the prepared statement protocol

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/RMySQL#117]
```
> dbGetQuery(con, "USE test")
Error: This command is not supported in the prepared statement protocol yet [1295]
```

This particular query is not that interesting, but others might fail as well.

In "master" branch.

**Comment by beanumber** [comment]
FWIW, I don't get this error on Ubuntu but @evagjekmarkaj does on Mac. We both are using MySQL 5.7.16.

**Comment by krlmlr** [comment]
1295 is `ER_UNSUPPORTED_PS`. Here's what [the internet](http://blog.ulf-wendel.de/2008/pdo_mysqlnd-prepared-statements-again/) says.

> If you hit an unsupported statement its not a bit deal: catch the 1295, ER_UNSUPPORTED_PS error and fall back to the non-prepared statement API. PDO does that for you – its transparent for the PHP user. You don’t need to worry about it.

Unfortunately, the non-prepared statement API seems to be an entirely different beast. A larger refactoring (essentially a new C++ class `MyNonPreparedResult`) will be necessary to fully support it.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
