### ISSUE TITLE
internal error in RS_DBI_getConnection: corrupt connection handle

### ISSUE THREAD

**Issue by cullan-liang** [rstats-db/RMySQL#119]
con <- dbConnect(
  MySQL(),
  m,
  user = "username", password = "password",
  host = "<myamazondatabase>",
  port = 3306
)

So everything was wroking but after a couple runs/refreshes on my shiny app, it says I have 16 connections open and I can no longer open any connections.

So, I tried running:
dbDisconnect(dbListConnections(MySQL()))

Then I got this:
 dbListConnections(MySQL())
[[1]]TRUE

Then I got this error: 
Error in .local(dbObj, ...) : 
  internal error in RS_DBI_getConnection: corrupt connection handle

Now, whenever I try to open my shiny app, I get the error on the datatableoutput (I query the database to generate this output):
internal error in RS_DBI_getConnection: corrupt connection handle

![image](https://cloud.githubusercontent.com/assets/14201864/11357577/909cbe8c-9236-11e5-9f6d-0132080038de.png)

Please help!!!

**Comment by krlmlr** [comment]
Which version of RMySQL are you using?

dbListConnections() will be deprecated soon. Is there a way to close the connection manually as soon as the Shiny app terminates?

**Comment by cullan-liang** [comment]
I just installed it using install.packages("RMySQL")
I am using 0.10.7 I believe.

Is there a better way to close connections other than using:

  statisticsPrediction <- function() {
    con <- dbConnect( ------ database info------)
    query <- (-----some SQL query-----)
    result <- dbGetQuery(conn = con, statement = query)
    all_cons <- dbListConnections(MySQL())
    for (con in all_cons)
      dbDisconnect(con)

    return(result)
}

**Comment by krlmlr** [comment]
`dbDisconnect()` is fine, it's just that `dbListConnections()` probably will be deprecated, so you'll need to remember all opened connections yourself.

**Comment by cullan-liang** [comment]
how else can i remember the connections? let's say I just refresh the page but keep the shiny app running on R, it will open another connection and I won't have access to the previously opened connection. is there a better way to manage this??

**Comment by cullan-liang** [comment]
Also, another question, so right now if I run a query that produces an invalid result (ie. inserting duplicate row), my shiny app will be forced to close. is there any way to prevent this from happening? (ie. somehow check if the statement is valid and returns a result)

**Comment by krlmlr** [comment]
This looks like a Shiny question that would be more suitable in another forum. Have you tried the development version of RMySQL?

@jeroenooms: Any idea what the problem here might be?

**Comment by cullan-liang** [comment]
Thank you so much for helping me out, I really appreciate it :)
I've looked around for hours but no answer to any of the two questions, but if there is someone on this forum that can guide me, it would be amazing!!

**Comment by krlmlr** [comment]
Can you install the development version using `devtools::install_github("rstats-db/RMySQL")` ?

**Comment by cullan-liang** [comment]
did that! so the initial problem has been solved already when I moved the open connection and close connection within each function, but I'm still having trouble with the second problem of error handling.

**Comment by krlmlr** [comment]
Use try() or tryCatch().

**Comment by cullan-liang** [comment]
its working now :) thanks so much!
