### ISSUE TITLE
Lack of BLOB support

### ISSUE THREAD

**Issue by gtmaskall** [rstats-db/RMySQL#123]
dbGetQuery(conn, "SELECT a FROM table") where a is a BLOB results in message about truncated field (and no data). Equivalent operation using RSQLite results in correct raw vector being returned, which can then be read as binary. My workaround with RMySQL is to request the server to cast the field to a HEX string, which you can then parse into a RAW and then read as binary. It would be great to have the same functionality for BLOBs in RMySQL as in SQLite.

**Comment by krlmlr** [comment]
Thanks. This looks like a known issue (#49), we will report there as soon as there is progress on that front.

**Comment by ElianoMarques** [comment]
gtmaskall - could you share you workaround in more detail? I'm facing the same issue and I'm trying to find a workaround this.

**Comment by gtmaskall** [comment]
Hi @ElianoMarques ,

Extract the BLOB by getting the server to convert the data to a HEX string, like
`SELECT HEX(myvar) AS myvar FROM mytable`
Then you can use a function I wrote to convert from string to raw [here](https://github.com/gtmaskall/blobUtilsR/blob/master/gtmBlob.R). I made it as fast as I could (there are some very slow ways of doing this!) Someone may well be able to optimize this even more, but it's acceptably fast even for quite large arrays that we deal with.

Hope this helps,
Guy

**Comment by ElianoMarques** [comment]
Thanks. I found another that just works nicely. If you store the object as 
```
paste(serialize(object),collapse = ";").``` 
Then store the object as text into Mysql. then use the following: 
```unserialize(as.raw(as.hexmode(strsplit(model_meta$model_meta, ";")[[1]])))```. Hope this also works.

**Comment by gtmaskall** [comment]
Thanks for the suggestion, but I don't have control of the stored data; I have to work with it "as is".

**Comment by krlmlr** [comment]
Closing as duplicate.
