### ISSUE TITLE
Cannot connect with SSL required

### ISSUE THREAD

**Issue by tanji** [rstats-db/RMySQL#131]
On the db side:

`GRANT USAGE ON *.* TO 'tanj'@'%' REQUIRE SSL;`

client side in .my.cnf:

```
[rstudio]
user=tanj
password=*******
ssl
ssl-ca=/home/tanj/MariaDB/mysql-ssl/ca-cert.pem
ssl-cert=/home/tanj/MariaDB/mysql-ssl/client-cert.pem
ssl-key=/home/tanj/MariaDB/mysql-ssl/client-key.pem
```

Connection is successful with CLI:

```
mysql --ssl --host remote -utanj -p
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 220
Server version: 10.1.10-MariaDB-log MariaDB Server

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> Bye
```

Connection fails in RStudio:

```
> mydb = dbConnect(MySQL(), dbname='test', host='remote', default.file="/home/tanj/.my.cnf", groups="rstudio")
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Access denied for user 'tanj'@'local' (using password: YES)
```

If SSL requirement is lifted on the client side, connection succeeds:

```
> mydb = dbConnect(MySQL(), dbname='test', host='remote', default.file="/home/tanj/.my.cnf", groups="rstudio")
> dbGetQuery(mydb, "SHOW STATUS LIKE 'ssl%'")
                    Variable_name                Value
1         Ssl_accept_renegotiates                    0
```

SSL is not enabled though.

Used last RMySQL 0.10.7 and MariaDB 10.1.10.

**Comment by krlmlr** [comment]
Does this also occur with the current development version? `devtools::install_github("rstats-db/RMySQL")`

**Comment by tanji** [comment]
Unfortunately I cannot install devtools, it fails on httr dependency:

```
> install.packages("httr")
Installing package into ‘/home/tanj/R/x86_64-pc-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
--2016-01-28 12:33:32--  https://cran.rstudio.com/src/contrib/httr_1.0.0.tar.gz
Resolving cran.rstudio.com (cran.rstudio.com)... 54.240.172.139
Connecting to cran.rstudio.com (cran.rstudio.com)|54.240.172.139|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-28 12:33:33 ERROR 404: Not Found.

Warning in install.packages :
  download had nonzero exit status
Warning in install.packages :
  download of package ‘httr’ failed
```

If you know a workaround...

**Comment by krlmlr** [comment]
Try another CRAN mirror via `install.packages(..., repos = "...")`

https://cran.r-project.org/mirrors.html

**Comment by tanji** [comment]
This did not go well...
```
Error in .Call("RMySQL_connection_create", PACKAGE = "RMySQL", host, user,  : 
  "RMySQL_connection_create" not available for .Call() for package "RMySQL"
```

**Comment by krlmlr** [comment]
Could you be a bit more specific: What OS are you on, did the installation of the dev version of RMySQL show any errors?

**Comment by tanji** [comment]
Using Arch Linux.

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"

No errors in installation, I would have communicated those otherwise.

**Comment by krlmlr** [comment]
This is very strange. Unfortunately, I don't have experience Arch Linux, so it will be difficult for me to replicate. Could you suggest a sequence of pacman (?) calls that will get me a system with R and MySQL in a Docker container?

**Comment by adamchainz** [comment]
I have this as well on Ubuntu, it only happened when moving from MySQL 5.6 to MariaDB, i.e. it only happens with `libmariadbclient`.

**Comment by adamchainz** [comment]
@tanji your error is the same as in #64

**Comment by adamchainz** [comment]
@krlmlr The only real difference I can find between RMySQL and two clients I know to work is that they call `mysql_ssl_set` explicitly. They are:

The mariadb CLI - `mysql`, here: https://github.com/MariaDB/server/blob/10.1/client/mysql.cc#L1356
Python's `mysqlclient` library, here: https://github.com/PyMySQL/mysqlclient-python/blob/7d289b21728ab1a94bb1f0210a26367c6714d881/_mysql.c#L649

I wrote a quick test program to check this:

```
#include <my_global.h>
#include <mysql.h>

int main(int argc, char **argv)
{
    MYSQL* pConn_ = mysql_init(NULL);
    // Enable LOCAL INFILE for fast data ingest
    mysql_options(pConn_, MYSQL_OPT_LOCAL_INFILE, 0);
    // Default to UTF-8
    mysql_options(pConn_, MYSQL_SET_CHARSET_NAME, "UTF8");

    mysql_ssl_set(pConn_, NULL, NULL, NULL, NULL, NULL);

    if (!mysql_real_connect(pConn_,
        "MYHOST",
        "MYUSERNAME",
        "MYPASSWORD",
        "MYDATABASE",
        3306,
        NULL,
        0)) {
      mysql_close(pConn_);
      printf("Failed to connect: %s", mysql_error(pConn_));
      exit(1);
    }
  printf("MySQL client version: %s\n", mysql_get_client_info());

  exit(0);
}
```

Without the `mysql_ssl_set` it fails, with it, it succeeds.

**Comment by msolano00** [comment]
Was this ever fixed? I am trying to connect to a DB using ssl and I get rejected every single time.

**Comment by krlmlr** [comment]
Yes, *RMariaDB* seems to handle SSL connections better.

**Comment by larsaam** [comment]
This still seems to be a problem. Can not connect a user that require SSL with R-Studio to MySQL 8.0.35, Ubuntu 22.04
