### ISSUE TITLE
SSL connection fails

### ISSUE THREAD

**Issue by seveas** [rstats-db/RMySQL#132]
When trying to connect to an ssl-enabled MySQL 5.6, I get the following failure:

```
$ Rscript pamtest.r 
Loading required package: DBI
Loading required package: methods
Error in .local(drv, ...) : 
  Failed to connect to database: Error: SSL connection error: unable to get issuer certificate
Calls: dbConnect -> .valueClassTest -> is -> is -> .local -> .Call
```

The script I use is very simple:
```
library(RMySQL)
con <- dbConnect(MySQL(), default.file="/home/dennis/.my.cnf");
```

And the my.cnf (hostname, user and password anonymized):
```
[client]
host = my-mysql-server
user = me
password = SuperSecret
no-auto-rehash
enable-cleartext-plugin
ssl
ssl-ca=ca-bundle.crt
ssl-verify-server-cert=1
```

These settings work with the mysql cli client and the perl and python bindings for mysql. If I disable ssl certificate verification, it still fails.

Relevant versions of things:
- Remote MySQL server: 5.6.27
- Local OS: Ubuntu 15.10
- Local libmysqlclient: 5.6.27
- R 3.2.2
- RMysql 0.10.4

**Comment by krlmlr** [comment]
Is this related to #131?

**Comment by seveas** [comment]
Probably not. I'm really new to R and was just testing our ssl+cleartext connections in as many languages as possible. When I found out how to upgrade RMysql from the system-provided 0.10.4 to 0.10.7 from cran, I tried that and the problem went away. So it already works in 0.10.7.

Apologies for the bogus bugreport!

**Comment by krlmlr** [comment]
Thanks for getting back. I'm wondering what the difference to #131 is, then.

**Comment by jchrom** [comment]
This error on Loki (based on Ubuntu 16.04) may be related:

```
Error in connection_create(host, username, password, dbname, port, unix.socket,  : 
  Failed to connect: SSL connection error: unable to get local issuer certificate
```

This is happening both on 0.10.9 and 0.11-5. But I wasn't getting it on Freya (=Ubuntu 14.04) with the same setup; this makes me think that the problem may not be with RMySQL, but I have no idea where to start. Can I provide some diagnostics? What info would be useful?

**Comment by bjornerstedt** [comment]
When I [asked this on](https://stackoverflow.com/questions/46886239/rmysql-ssl-connection-error) Stackexchange, it was suggested that I post it here.

Summary:

I am trying to connect to a MySQL server with SSL. Everything works fine when I use the mysql client, but with RMySQL::dbConnect I get the error:

```
Error in .local(drv, ...) :  
Failed to connect to database: Error: SSL connection error: unable to get issuer certificate
```
When I set up a test server on another server everything works, but not on the server

Details:

Connecting to the server (MySQL: 5.5.54-log MySQL Community Server (GPL)) with the command line client works fine:

```
mysql --host [servername] -u [user] -p --ssl-ca=/home/jonas/ssl-ca.pem
WARNING: --ssl is deprecated and will be removed in a future version. Use --ssl-mode instead.
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 193009
Server version: 5.5.54-log MySQL Community Server (GPL)
```
But when I try:

```
mydb = dbConnect(MySQL(), dbname='sh', host='[hostname]', default.file="/home/jonas/my.cnf", group="client")
```
I get the error above. The configuration file my.cnf is as follows:

```
[client] 
user=... 
password=... 
ssl-ca=/home/jonas/ssl-ca.pem  

[sunet] 
user=... 
password=... 
ssl-ca=/home/jonas/client-ssl/ca.pem
```

On my test server (Mysql version: 5.7.19-0ubuntu0.16.04.1) the corresponding command works:
```
mydb = dbConnect(MySQL(), dbname='sh', host='[hostname]',  default.file="/home/jonas/my.cnf", group="sunet")
```
The pem files have the same file privileges set. I am using RMySQL version 0.10.13 and R version 3.2.3.
