### ISSUE TITLE
Fields truncated when contain certain characters like "\0"

### ISSUE THREAD

**Issue by mekkim** [rstats-db/RMySQL#139]
I use RMySQL to query a database with lengthy bug descriptions that sometimes include binary dumps.  The resulting character fields can ~~be very large.  There's a limitation somewhere that leads to them being truncated.~~ contain all sorts of characters which ideally should be handled verbatim.  When such fields are read, they are truncated at such characters, for example, "\0".

Is there a way to ~~add an option to change the field size to avoid the truncation~~ force RMySQL to treat such characters as verbatim and not truncate? Or is it a hard limitation of R 64-bit?  or `dbFetch()`?  Example warning when using `dbGetQuery()` on table with some ~~very large~~ character fields with unusual characters:

```
Warning in dbFetch(rs, n = -1, ...) :
    internal error: row 420671 field 3 truncated
```

**Comment by krlmlr** [comment]
Which version of RMySQL are you using? A reproducible example would be very helpful.

**Comment by mekkim** [comment]
RMySQL 0.10.8 (latest CRAN)
DBI 0.3.1
R 3.2.3 64-bit Windows

The query in R is fairly generic: `dbGetQuery(conn = connectionName, statement = 'SELECT * FROM longdescs;');` 

My best guess is that this is field 3 of row 420671 as per the error.  Upon inspection, it looks like it may be a problem not with very big fields getting truncated, but rather with something else going on with how special characters are treated.  It seems like the "\0" characters trigger the truncation and the resulting data is truncated right after the "d" just before the first "\0" on the second last line as seen below:

> 'Google gives us a neat \"bookmarklet\" that looks like this:\n\n(name) Google Search\n\n(url) javascript:q=document.getSelection();for(i=0;i<frames.length;i++){q=frames\n[i].document.getSelection();if(q)break;}if(!q)void(q=prompt(\'Enter text to \nsearch using Google. You can also highlight a word on this web page before \nclicking Google Search.\',\'\'));if(q)location.href=\'http://www.google.com/search?\nclient=googlet&q=\'+escape(q)\n\n\nSince I want this to be in my personal toolbar, I open \"manage bookmarks\" and \ndrag it to the \"personal toolbar\" folder.  But after I do that the bookmark \nlooks like this:\n\n(name) text to search using Google. You can also highlight a word on this web \npage before clicking Google Search.\',\'\'));if(q)\nlocation.href=\'http://www.google.com/search?client=googlet&q=\'+escape(q)\n\n(url) javascript:q=d\0\0\0\0\0\0ocument.getSelection();for(i=0;i<frames.length;i++){q=frames\n[i].document.getSelection();if(q)break;}if(!q)void(q=prompt(\'Enter'

**Comment by mekkim** [comment]
Additional note, this is what that text looks like when displayed in the graphical interface to the underlying Bugzilla database: [First comment for bug 52519](https://bugzilla.mozilla.org/show_bug.cgi?id=52519#c0)

Looking at the page source, it seems like it's first passed through some [line-wrapping JavaScript code](https://bugzilla.mozilla.org/js/comments.js?1459257820) that may be handling the "\0" characters so that they never reach the browser.

**Comment by krlmlr** [comment]
The query doesn't tell anything about the schema or the data in the database.

As far as I know, R does not support strings with embedded NUL characters.

Could you please try with the lastest DBI + RMySQL from GitHub?

```
devtools::install_github(c("rstats-db/DBI", "rstats-db/RMySQL"))
```

**Comment by mekkim** [comment]
Ah, that would be it.  R does not support embedded NUL characters ("\0") in strings.

data.table's `fread()` bypasses this problem when reading from CSV files by embedding shell pre-processing in the command (such as with sed, PERL, etc.) of the CSV file before it is read.  Would there be any viable way to do something similar with RMySQL at the field-level?  External calls to shell commands for every field are obviously not viable for non-trivial databases, but I don't know much about the internals, so I'm unsure if there's an easier place that very basic processing could be done on the fields.

The issue here is that I'm frequently operating on very large databases with unknown contents, data, and no schema.  An on-input filter that substitutes values that R does not allow, such as embedded null "\0" would be handy, but may not be worth adding for my particular use case.  Of course, with known schema/data, etc., this wouldn't be an issue.

If you don't see a relatively straightforward way of addressing this, the issue should be closed as and I'll just deal with truncation at embedded NULs.  At least I now know what's going on! :)

Thanks!

**Comment by krlmlr** [comment]
Thanks for bringing this up. RMySQL interna are C++, it's the conversion to an R string where the trimming occurs.

For your use case, try to cast the value to a `varbinary` to get hold of the raw representation, as in

```
SELECT BINARY('123')
```

**Comment by kasun61** [comment]
I am encountering the same issue trying to concatenate a set of columns which have '0' in them as values. 
 col1 col2 col3
    0    0    0
    0    0    0
    0    0    0
    0    0    0

df.comb <- dbGetQuery(con, "SELECT CONCAT(CONVERT(col1, CHAR(50)), CONVERT(col2, CHAR(50))) FROM tbl LIMIT 1000")

which gives me the warning:
 In dbFetch(rs, n = -1, ...) : internal error: row 71 field 0 truncated

Can you please explain how the proper CAST/ CONVERT is done to avoid embedded NUL issue.

Thank you.
