### ISSUE TITLE
Update existing records using primary key

### ISSUE THREAD

**Issue by debsush** [rstats-db/RMySQL#152]
Suppose I have a table (say TableA) like below
Primary_Key       Name      Value
101                     Dan             67
102                     John          109
103                     Danio          30
104                     Tomar         31

Now I fetched a new table as below (say TableB)
Primary_Key       Name          Value
102                     Johnny          901
103                     Danone          301

I want to update table A using data from table B where the primary key is matching (only the records 102 and 103) while the remaining records in TableA should remain unchanged (101 and 104)

Current append = TRUE simplyappends the tableB data while overwrite= TRUE will replace TablaA contents with TableB contents

Is this doable?

**Comment by AkhilNairAmey** [comment]
This is old, but for anyone looking this may be an quick solutions:

https://github.com/AkhilNairAmey/dbUpdateTable

**Comment by debsush** [comment]
Thank you Akhil.  This is super helpful!!!
