### ISSUE TITLE
SSL connection error: certificate verify failed

### ISSUE THREAD

**Issue by feedesam** [rstats-db/RMySQL#153]
I manage to connect correctly to the mysql server with a ssl certificate, but when i get the message that " MySQL server has gone away [2006]" and I try to reconnect I get the following error:
Error: Failed to connect: SSL connection error: certificate verify failed

```
library(devtools)
dev_mode(on=T)
devtools::install_github("RcppCore/Rcpp")
devtools::install_github("rstats-db/DBI")
devtools::install_github("rstats-db/RMySQL")

library("DBI")
library("RMySQL")

mydb = dbConnect(MySQL(), user='xxx', password='xxx', dbname='xxx', host='xxx',
                 ssl.ca = '/Users/xxx.pem')
```

Session info:

R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.11-2   DBI_0.4         devtools_1.11.1 rpart_4.1-10    ggplot2_2.1.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4.5    digest_0.6.9     withr_1.0.1      grid_3.2.4       plyr_1.8.3       R6_2.1.2         gtable_0.2.0     git2r_0.14.0  
 [9] scales_0.4.0     httr_1.1.0       curl_0.9.7       tools_3.2.4      munsell_0.4.3    colorspace_1.2-6 memoise_1.0.0

**Comment by explodecomputer** [comment]
I'm having the same problem. This works in CLI:

```
mysql -u xxx -p -h xxx -P xxx --ssl-ca=xxx.pem
```

This works in python:

```
import sys
import mysql.connector
from mysql.connector.constants import ClientFlag

config = {
    'user': 'xxx',
    'password': 'xxx',
    'host': 'xxx',
    'client_flags': [ClientFlag.SSL],
    'ssl_ca': 'xxx.pem',
    'port':xxx,
    'database': 'xxx'
}

cnx = mysql.connector.connect(**config)
```

But this doesn't work in R:

```
devtools::install_github("rstats-db/RMySQL")
library(RMySQL)

mydb <- dbConnect(
    RMySQL::MySQL(), 
    username='xxx', 
    password='xxx', 
    dbname='xxx', 
    host='xxx', 
    port=xxx, 
    ssl.ca="xxx.pem", 
    client.flag=2048
)
```

I get the following error:

```
Error in connection_create(host, username, password, dbname, port, unix.socket,  : 
  Failed to connect: SSL connection error: certificate verify failed
```

Omitting the `client.flag` argument doesn't seem to change the behaviour.

Session info:

```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.11-3

loaded via a namespace (and not attached):
[1] tools_3.3.1 DBI_0.5-1   Rcpp_0.12.8
```

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
