### ISSUE TITLE
"RMySQL_connection_create" not available for .Call() for package "RMySQL on windows7-64

### ISSUE THREAD

**Issue by yanggeorge** [rstats-db/RMySQL#156]
I have installed development version of RMySQL . On CentOS ,there is no problem. But on Windows, I get the following error when I create connection . 
`Error in .Call("RMySQL_connection_create", PACKAGE = "RMySQL", host, user,  : 
  "RMySQL_connection_create" not available for .Call() for package "RMySQL"`

So, I compare the install processes and find that on linux `RcppExports.cpp` is compiled as such 
`g++ -m64 -I/usr/include/R -DNDEBUG -I/usr/include/mysql -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
In file included from RMySQL_types.h:5:0,
                 from RcppExports.cpp:4:`
and at the end RMySQL.so is linked with all object files
`g++ -m64 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o RMySQL.so MyConnection.o RMySQL-init.o RcppExports.o connection.o result.o timegm.o version.o -L/usr/lib64/mysql -lmysqlclient -lpthread -lz -lm -lssl -lcrypto -ldl -L/usr/lib64/R/lib -lR`

But on windows , I cannot find this.
**so I want to know How can I compile these cpp files on windows and generate the RMySQL.dll file**

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
