### ISSUE TITLE
Needs to implement `dbQuoteString(MySQLConnection, SQL)` and `dbQuoteIdentifier(MySQLConnection, SQL)` 

### ISSUE THREAD

**Issue by bborgesr** [rstats-db/RMySQL#158]
From [DBI's documentation](https://github.com/rstats-db/DBI/blob/master/R/quote.R#L20):

> Note that because of the way that S4 dispatch finds methods and because SQL inherits from character, if you implement (e.g.) a method for `dbQuoteString(MyConnection, character)`, you will also need to implement `dbQuoteString(MyConnection, SQL)` - this should simply return `x` unchanged.

Currently, only `dbQuoteString(MySQLConnection, character)` and `dbQuoteIdentifier(MySQLConnection, character)` exist. Am I missing something?

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
