### ISSUE TITLE
dbWriteTable use insert insead of load data infile

### ISSUE THREAD

**Issue by maciejorlos** [rstats-db/RMySQL#186]
Hi,
I update Rmysql and DBI to newest dev versions. I found that dbWritetable slow down because of using insert to load data.frame to mysql data.base. I used before   0.10.9 version of rmysql, which was using load data infile command to create new table. It would be great if this options could return.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
