### ISSUE TITLE
Support for MySQL 5.7 JSON

### ISSUE THREAD

**Issue by vchav73** [rstats-db/RMySQL#189]
I get the following when attempting to use a MySQL 5.7 database which uses MySQL's new JSON data type. Would be nice if JSON columns were automatically converted to R objects. It has to be done manually for now.

```
In addition: Warning message:
In .local(conn, statement, ...) :
  unrecognized MySQL field type 245 in column 1 imported as character
```

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
