### ISSUE TITLE
Cannot connect to a remote MySQL server from Mac

### ISSUE THREAD

**Issue by c5sire** [rstats-db/RMySQL#192]
On my Mac OS 10.12.3 I can correctly connect to a local MySQL database. But not to a MySQL database on a remote server. However, I can also connect correctly to the remote database from Windows using RMySQL.

On my Mac I installed the mariadb connector via brew. I also tested using both the CRAN stable version of RMySQL and using the github development versions.

I use a .my.cnf file for the parameters.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
