### ISSUE TITLE
ssl.cipher doesn't like self-signed cert

### ISSUE THREAD

**Issue by maryskalicky** [rstats-db/RMySQL#195]
This may not be an issue with rstats-db/RMySQL but I'm not sure.

I'm trying to connect to an Aptible database.   These databases have self-signed certs and require ssl but do not require a key or cert to connect.  I've tried the following:

con = dbConnect(RMySQL::MySQL(), user = 'aptible', host = 'localhost.aptible.in', password = 'password', dbname = 'db', port = 58099, ssl.cipher = 'DHE-RSA-AES256-SHA')
Error in connection_create(host, username, password, dbname, port, unix.socket,  :
 Failed to connect: SSL connection error: self signed certificate

Is this an issue within rstats-db? Or is there a another way to accomplish this that I could try?

**Comment by adam301** [comment]
I have the same problem when using ssl.ca=... option

**Comment by maryskalicky** [comment]
Are you using libmariadb?  

We had this issue because we were using libmariadb ("Connector/C") as opposed to libmysqlclient, which has different (and apparently unconfigurable) defaults for SSL verification.

We fixed this in the Docker image by installing the libmysqlclient-dev package rather than the libmariadb-client-lgpl-dev package (which is that "Connector/C" package), before installing the rstats-db/RMySQL package.

**Comment by adam301** [comment]
I am using R for windows and shinyapps.io for deployment. I have problem with self signed certificate only on the windows client, when application is deployed to shinyapps.io it works fine.

**Comment by krlmlr** [comment]
Thanks. Have you installed RMySQL from CRAN or from GitHub?

**Comment by adam301** [comment]
Tried both CRAN and GitHub versions.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
