### ISSUE TITLE
Unable to find an inherited method for function ‘dbListFields’ for signature ‘"MySQLConnection"’

### ISSUE THREAD

**Issue by martinschmelzer** [rstats-db/RMySQL#199]
Got a homebrewed isntall of XAMPP. Connected to the db with 

```
con <- dbConnect(RMySQL::MySQL(), host = 'localhost', 
                 user ='user', password = 'pw', 
                 unix.socke='/Applications/XAMPP/xamppfiles/var/mysql/mysql.sock',
                 dbname = 'dbname')
```

`dbListTables(con)` works fine and returns the single table that is inside the db. But when I then try

`dbListTables(con, 'tablename')` I get:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbListFields’ for signature ‘"MySQLConnection"’

Additional info:
Mac OS Sierra, R 3.4, DBI 0.6-1, RMySQL 0.11-5 

<MySQLConnection>
  Host:    localhost
  Server:  10.1.21-MariaDB
  Client:  5.5.1

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
