### ISSUE TITLE
SSL CA fails

### ISSUE THREAD

**Issue by mikeBohneTruth** [rstats-db/RMySQL#201]
I am trying to use RMySQL to connect to an AWS RDS MySQL server.  We recently set up SSL on the server and I am no longer able to login using the production install of RMySQL.  I was previously able to connect without SSL certificate.  Reading in other issues I see that using the development install sometimes works, but in this case establishes one connection and then won't create a new connection to server without closing RStudio.  Doesn't work for multiple locations of data.

I verified that there is nothing wrong with server setup by establishing connection via Python and running simple queries.

(Note: that using the client.flag=2048)

Command being used for Production install connection: 

drv <- dbDriver("MySQL")
dbConnect(drv, host='hostLocation', user = 'username', password=pw, dbname='dbname', port=3306, ssl.ca='location of pem file', client.flag=2048)

Output:
Error in .local(drv, ...) : 
  Failed to connect to database: Error: Bad handshake

Same command for Dev install connection yields this on the second try:

Error in connection_create(host, username, password, dbname, port, unix.socket,  : 
  Failed to connect: SSL connection error: certificate verify failed

I'm using macOS Sierra Version 10.12.4 but a colleague is unable to connect via windows as well; 
RStudio Version 1.0.136; 
RMySQL version 0.10.11 for production install;
 and these commands to get the development version: 
devtools::install_github("rstats-db/DBI")
devtools::install_github("rstats-db/RMySQL")

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
