### ISSUE TITLE
dplyr cannot connect to table

### ISSUE THREAD

**Issue by ijlyttle** [rstats-db/RMySQL#27]
Hi, 

I am using the development version of `RMySQL` (maybe I'm not supposed to).

I don't know if this is a `dplyr` issue or an `RMySQL` issue, but I get an error when I try to connect a `dplyr` `tbl` to an `RMySQL` table.

The frustrating thing is that I can't give a reproducible example because I can't supply the database.

I am running using a local implementation of MySQL.

```
> sql_src <- src_mysql("test")

> sql_src
src:  mysql 5.6.22 [root@localhost:/test]
tbls: grid, image, image_sub, intensity

> sql_image <- tbl(sql_src, from = "image")
Error: select is not a character vector
```

Looking through the reverse dependency log, I see something similar.

https://github.com/rstats-db/RMySQL/blob/79039c7661b3920a6c8ffa62f54581055b7fad2b/revdep/summary.md

Section dplyr:

```
Loading required package: RMySQL
Loading required package: DBI
Error: select is not a character vector
```

I am happy to try to be more specific, but I am at a loss for now.

Thanks.

**Comment by hadley** [comment]
Thanks for catching this! I was using the wrong DBI method in dplyr, and I'd broken the old (undefined) behaviour.

**Comment by ijlyttle** [comment]
As usual for me, it was more of a stumble-into than a catch...

If needed, I'm happy to open an issue at dplyr and/or close this one.

Thanks!

**Comment by hadley** [comment]
Ooops, I thought it already was in dplyr. Anyway, it's fixed now

**Comment by ijlyttle** [comment]
Cool! Thanks!
