### ISSUE TITLE
Authors

### ISSUE THREAD

**Issue by jeroenooms** [rstats-db/RMySQL#32]
The BDR says:

 > Authors@R field should be a call to person(), or combine such calls.

Not sure what is wrong.

**Comment by hadley** [comment]
You now must explicitly call `person()`

**Comment by jeroenooms** [comment]
I [updated](https://github.com/rstats-db/RMySQL/blob/master/DESCRIPTION) it, but now only the first author shows up in the pdf manual.

**Comment by hadley** [comment]
That looks correct to me, so if you want a fix to the pdf, you'll need to complain on r-devel :/
