### ISSUE TITLE
Linux compilation (and fix)

### ISSUE THREAD

**Issue by jourquin** [rstats-db/RMySQL#36]
Hi,

I've encountered a problem while compiling RMySQL on a rpm based system (Fedora 21, x64). 

For some reason, I had to install the i686 version of MySQL/Mariadb some time ago, in addition to the 64bit version. Later, I remove the i686 packages. 

When compiling RMySQL (64), the process ended with an error as it could't find libmysqlclient. It comes out that "configure" relies on the existence of /usr/lib/mysql or /usr/lib64/mysql to choose between the 32 ou 64 bit version to link to. Unfortunately, removing a package doesn't (always?) remove the relevant directory structure. In my case, /usr/lib/mysql was still present, even if empty.

To solve this issue, I deleted the (empty ) /usr/lib/mysql, and RMySQL compiled successfully. 

Maybe the "configure" file should be modified in order not to rely on the existence of a given directory ? An (unperfect) fix is to test "lib64" before "lib" in "configure"

**Comment by jeroenooms** [comment]
Sure we can turn it around. You shouldn't be installing i686 packages on x64 though, that is asking for trouble :)

**Comment by hadley** [comment]
Is this resolved now?

**Comment by jeroenooms** [comment]
This should no longer be an issue because we use `mysql_config`
