### ISSUE TITLE
How to suppress typecasting warnings

### ISSUE THREAD

**Issue by amstilp** [rstats-db/RMySQL#37]
After upgrading RMySQL 0.10 from 0.9-3, I started getting many warnings saying:
```
1: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 0 imported as numeric
```
While it can be useful to know that the typecasting from MySQL to R is happening, it's also annoying to continually get these warnings all the time. My database uses unsigned integers as primary keys in every table, so I get this with every query. I can think of some possible ways to address this:
1) add an option to suppress typecasting warnings
2) allow the user to specify how to cast MySQL types to R types

To fix this, I will probably change the MySQL types in the database to use just integers, but other people might have this problem too. Thanks.

If it's useful, here's all of sessionInfo():
```
R version 3.1.2 (2014-10-31)
Platform: x86_64-unknown-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.10 DBI_0.3.1  
```

**Comment by noktilux** [comment]
This is truly an annoying feature.  Most of my columns are UNSIGNED integers and I am running large queries all the time.  On top of this, there is some mystery error that occurs and the only sense I can make of it is that it's triggered when a certain muber of columns is exceeded (seems to be 203 for a particular table I am testing). 

Is there a way to revert to the old version, which I was very happy with?

**Comment by hadley** [comment]
I'm planning a rewrite of RMySQL in a couple of weeks, and I'll fix this then. Until then, you can easily suppress the warnings with `suppressWarnings()`

**Comment by noktilux** [comment]
hadley.

Thanks for the reply.  Can you please have a look at this too, before the rewrite:
https://github.com/rstats-db/RMySQL/issues/40

Until the fixes, do you know how I can find / install the older version ( "0.9-3' )?

Cheers.

**Comment by hadley** [comment]
Should be gone now. Please let me know if you still have problems (and please include a reproducible example)

**Comment by JKelly12** [comment]
Even using version 0.10.2, I am still receiving this warning. An example on a very simple table is included below.

```
> library(RMySQL)
Loading required package: DBI
> conn <- dbConnect(MySQL(), user = user, password = pass, host = server, port = 3306)
> dbGetQuery(conn, "SELECT * FROM test.int_test")
  id
1  1
2  2
Warning message:
In .local(conn, statement, ...) :
  Unsigned INTEGER in col 0 imported as numeric
> sessionInfo()
R version 3.1.3 (2015-03-09)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.1 LTS

locale:
[1] C

attached base packages:
[1] graphics  grDevices utils     datasets  stats     methods   base     

other attached packages:
[1] RMySQL_0.10.2     DBI_0.3.1         gearman_0.1-5     RJSONIO_1.3-0

loaded via a namespace (and not attached):
[1] rredis_1.6.9 tools_3.1.3 
> dbGetQuery(conn, "SHOW CREATE TABLE test.int_test")
     Table                                                                                                                           Create Table
1 int_test CREATE TABLE `int_test` (\n  `id` int(10) unsigned NOT NULL DEFAULT '0',\n  PRIMARY KEY (`id`)\n) ENGINE=InnoDB DEFAULT CHARSET=latin1
```

**Comment by hadley** [comment]
@JKelly12 the dev version is 0.11.0.9000

**Comment by JKelly12** [comment]
Ah, okay. Thanks for the quick reply!

**Comment by yinghawl** [comment]
Hi, Hadley

I ran into the same issue. May i know what I can fix it? Thank you!

> library(RMySQL)
> hg19<-dbConnect(MySQL(),user="genome",db="hg19",host="genome-mysql.cse.ucsc.edu")
> query<-dbReadTable(hg19,"affyU133Plus2")
There were 16 warnings (use warnings() to see them)
> warnings()
Warning messages:
1: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 0 imported as numeric
2: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 1 imported as numeric
3: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 2 imported as numeric
4: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 3 imported as numeric
5: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 4 imported as numeric
6: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 5 imported as numeric
7: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 6 imported as numeric
8: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 7 imported as numeric
9: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 8 imported as numeric
10: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 11 imported as numeric
11: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 12 imported as numeric
12: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 13 imported as numeric
13: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 15 imported as numeric
14: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 16 imported as numeric
15: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 17 imported as numeric
16: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 18 imported as numeric
R version 3.1.3 (2015-03-09)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.10.2  DBI_0.3.1      RCurl_1.95-4.5 bitops_1.0-6  

loaded via a namespace (and not attached):
[1] tools_3.1.3

**Comment by hadley** [comment]
@yinghawl install the dev version?

**Comment by DK-R** [comment]
Hi hadley,
Same issue as yinghawl, how I can check if dev version installed?

R version 3.2.0 (2015-04-16)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_GB.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.10.3 DBI_0.3.1    

loaded via a namespace (and not attached):
[1] tools_3.2.0

**Comment by DK-R** [comment]
sorry saw now additional 2 lines:
.
.
16: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 18 imported as numeric
17: In dbFetch(rs, n = -1, ...) : error while fetching rows
18: In dbGetQuery(conn, paste("SELECT * FROM", name)) : pending rows

**Comment by tvmanikandan** [comment]
I am using 0.10.5 version. Still I get the below warnings and also not all records are fetched from db.

Warning messages:
1: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 0 imported as numeric
2: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 2 imported as numeric
3: In .local(conn, statement, ...) :
  Unsigned INTEGER in col 12 imported as numeric
4: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 13 imported as character

Please help.

-Mani

**Comment by sanjmeh** [comment]
Alright. So the typecast warning persists. I am not bothered about the warning itself. The fact that R is unable to recognise DATE fields of MySQL and coerces them to a character type is troubling me. Ideally any Y-M-D HH:MM:SS (TIMESTAMP) should easily be retained as POSIXct type in R. 

The warning mentions **type 7** ...
>  unrecognised MySQL field type 7 in column 3 imported as character

**Comment by eddelbuettel** [comment]
November 2017, and the warning is still there:

```
R> source("fetchData.r")
Warning messages:
1: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 1 imported as character
2: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 12 imported as character
3: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 15 imported as character
4: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 18 imported as character
5: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 21 imported as character
6: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 24 imported as character
7: In .local(conn, statement, ...) :
  unrecognized MySQL field type 7 in column 27 imported as character
R> packageVersion("RMySQL")
[1] ‘0.10.13’
R>
```

**Comment by eddelbuettel** [comment]
I should add that just switching to RMariaDB alleviated the issue for me.

**Comment by daattali** [comment]
April 2019 update: just installed the latest version from GitHub, and I still do see these warnings

**Comment by jcpsantiago** [comment]
@daattali using RMariaDB like @eddelbuettel suggested works for me. Not really a solution I guess, but it's a good alternative.

**Comment by daattali** [comment]
@jcpsantiago unfortunately mariadb was my first choice, but I tried switching to mysql because of [this issue](https://github.com/r-dbi/RMariaDB/issues/69) (that is supposedly resolved also, but I'm still getting :smile: )

**Comment by stilsons** [comment]
Thank you, Hadley!

**Comment by nxp10225** [comment]
I have the same problem. It's not so much that the warnings bother me, but I have many unsigned integer columns that are in fact bitmasks or flags to be used with bitwiseAnd() & Co. I really don't want them to be converted to doubles. Also there's some weirdness stemming from base-2 integers not precisely mapping onto base-2 floats which makes me uneasy. I'm assuming R does that because MySQL's larger unsigned ints don't fit into R's signed int, which makes sense, but all my flag fields are SMALLINT and TINYINT, so they easily fit into an R integer. I'm assuming that in RMySQL there's a lookup table for functions that convert MySQL types to R types. Shouldn't this be an easy fix?

(Then there are datetime fields which should easily map onto POSIXct but I won't press the issue because anything to do with date and time is always a great hassle)
