### ISSUE TITLE
RMySql breaks dbConnect for postgres

### ISSUE THREAD

**Issue by kurtharriger** [rstats-db/RMySQL#39]
After loading RMySQL I get errors excuting dbConnect for postgres: 

```
library(RPostgreSQL)
drv <- dbDriver("PostgreSQL")
con <- dbConnect(drv, dbname="mydb", user="myuser", password="mypass", host="myhost")
dbListTables(con)

library(RMySQL)
con <- dbConnect(drv, dbname="mydb", user="myuser", password="mypass", host="myhost")

## Error in as.integer(from) : 
##  cannot coerce type 'S4' to vector of type 'integer' 
```

**Comment by jeroenooms** [comment]
Duplicated https://github.com/rstats-db/RMySQL/issues/28.

**Comment by kurtharriger** [comment]
The following version does still work: 
RMySQL_0.9-3  

To install old version from terminal window run the following then restart R. 
```
wget http://cran.r-project.org/bin/macosx/contrib/3.0/RMySQL_0.9-3.tgz
R CMD INSTALL RMySQL_0.9-3.tgz
```

**Comment by jeroenooms** [comment]
Could you try to install this version and see if this has the problem?

```s
library(devtools)
install_github("rstats-db/RMySQL@clean")
```

**Comment by phurvitz** [comment]
library(devtools)
install_github("rstats-db/RMySQL@clean")

just worked for me.

**Comment by westonplatter** [comment]
Note for future google searchers, the `clean` branch was deleted. Therefore, you should use master.

```sh
library(devtools)
install_github("rstats-db/RMySQL@master")
```
