### ISSUE TITLE
Failed to install source on OSX with 'mysql' brew package

### ISSUE THREAD

**Issue by gaborcsardi** [rstats-db/RMySQL#42]
Why not just use `mysql_config`, if it is available?

**Comment by jeroenooms** [comment]
Yes that is the pipeline. Dupe https://github.com/rstats-db/RMySQL/issues/38.

**Comment by gaborcsardi** [comment]
Ooops, searched for 'OSX' only, sorry.

**Comment by jeroenooms** [comment]
There is a complication though, because we have to avoid dynamic linking on the CRAN build server.

**Comment by gaborcsardi** [comment]
I see. I don't really need it personally, just wanted to have *some* mysql server on OSX, not just the client library, for testing. But noticed that the mariadb package works out of the box, so I am fine with that.
