### ISSUE TITLE
where did `dbGetQuery` go?

### ISSUE THREAD

**Issue by stevenpollack** [rstats-db/RMySQL#43]
It seems the transition from `0.9.3` to `0.10.0` has dropped `dbGetQuery` from the package NAMESPACE, with no reflection in the documentation. Can anyone explain the change in the API?

**Comment by hadley** [comment]
Because the default method (provided by DBI) is adequate.

**Comment by stevenpollack** [comment]
So, is there anywhere to suggest how we can replace calls to `dbGetQuery`?

**Comment by hadley** [comment]
Just use it

**Comment by stevenpollack** [comment]
I'm getting an NAMESPACE error when I call it. And `RMySQL:::dbGetQuery` isn't alleviating that.

**Comment by hadley** [comment]
It's in DBI, so you'd do `DBI::dbGetQuery()`
