### ISSUE TITLE
Some users are experieincing some odd behavior when using both MySQL and PostgreSQL

### ISSUE THREAD

**Issue by drknexus** [rstats-db/RMySQL#46]
Some users are experiencing some odd behavior with RPostgreSQL after the loading of RMySQL.

For example:
```
library(RPostgreSQL)
library(dplyr)
src_postgres(yourInformationhere)
```
Works, but
```
library(RMySQL)
library(RPostgreSQL)
library(dplyr)
src_postgres(yourInformationhere)
```

Does not appear to work as expected.  I'm not sure what other debugging information to provide.  If there is a guide for that, please be so kind as to point me in that direction.  I can see that your group has produced RPostgres and it does appear to work alongside RMySQL without issue, but it is still surprising/undesirable that the presence of RMySQL would cause another package to fail to operate.

See:  http://stackoverflow.com/questions/16403460/dbconnect-with-r-3-0-on-ubuntu-12-04-x64-error-in-as-integerfrom-cannot-co/27798926#27798926

**Comment by hadley** [comment]
This is fixed in the dev version.
