### ISSUE TITLE
Compiler warning

### ISSUE THREAD

**Issue by jeroen** [rstats-db/RMySQL#52]
@hadley I think this was introduced recently?

``` c
In file included from ./MyBinding.h:6:
./MyTypes.h:19:10: warning: enumeration values 'MYSQL_TYPE_TIMESTAMP2',
      'MYSQL_TYPE_DATETIME2', and 'MYSQL_TYPE_TIME2' not handled in switch
      [-Wswitch]
  switch(type) {
         ^
./MyTypes.h:61:1: warning: control may reach end of non-void function
      [-Wreturn-type]
}
^
2 warnings generated.
```

**Comment by hadley** [comment]
Oh I bet it's with your libmariadb update. I'll take a look

**Comment by jeroenooms** [comment]
This is actually on osx.

**Comment by hadley** [comment]
Hmmm, maybe you and I have different client versions? I don't seem to get this error locally.

I wonder what the best way of handling this is. I need to provide a default statement for that switch, but what should it do? It could either throw an error, or it might be possible to use character for unknown variable types, and hope MySQL coercion does something reasonable.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
