### ISSUE TITLE
dbWriteTable and dbRemoveTable return same "corrupt resultSet" error after successfully completing

### ISSUE THREAD

**Issue by stevenpollack** [rstats-db/RMySQL#53]
I'm not sure if this is standard behaviour, but when using `dbWriteTable` or `dbRemoveTable`, I get the error:
```
Error in is(object, Cl) : corrupt resultSet, missing fieldDescription
```
To give you something reproducible
* I started a local mysql server (`mysql-server` version 5.5.41-0ubuntu0.14.04.1), `-u root`, `-p alpine` and added `testTable` to the `mysql` db:
```
$ mysql --user=root --password=alpine mysql
> CREATE TABLE testTable (id text);
```
* inside R with `RMySQL` version 0.10.2 and `DBI` version 0.3.1.9008:
```R
X <- DBI::dbConnect(drv=RMySQL::MySQL(), user = "root", password = "alpine", dbname="mysql")
DBI::dbExistsTable(conn = X, name = "testTable") # TRUE
DBI::dbWriteTable(conn = X, name = "testTable", value = data.frame(id = "1"), row.names = FALSE, append = TRUE) # throws error above
DBI::dbReadTable(conn = X, name = "testTable") # drops data.frame in "value", above
DBI::dbRemoveTable(conn = X, name = "testTable") # throws error above
DBI::dbExistsTable(conn = X, name = "testTable") # FALSE

**Comment by hadley** [comment]
Can you please try the dev version of RMySQL?

**Comment by stevenpollack** [comment]
Turns out, the dev version does not have this issue.

:+1: 

Just out of curiosity, why was I running into this error?

**Comment by hadley** [comment]
I have no idea. The old C code was a diabolical mess, so I rewrote it from scratch.

**Comment by stevenpollack** [comment]
You're the fucking man.

**Comment by krlmlr** [comment]
@jeroenooms: This is consistently popping up in the revdep check for DBI (https://github.com/rstats-db/DBI/pull/90/commits/5609db868753ba7e93215d03f07bef574c989ff9#diff-1890a66bd55e1dc6bab18e8ff5c17ce5R443). Any idea?

**Comment by krlmlr** [comment]
Got it, It's a change in the behavior of DBI::dbGetQuery().
