### ISSUE TITLE
Error: Out of range value for column 'n' at row 1 [1264]

### ISSUE THREAD

**Issue by aclemen1** [rstats-db/RMySQL#54]
Hi @hadley,

The following code fails with the aforementioned error:

```
test <- data.frame(n = c(1, NA))
dbWriteTable(conn = conn, name = "test", value = test, overwrite = T)
```

Thanks and best regards.

-- Alain

**Comment by krlmlr** [comment]
Thanks. Do you still see this behavior with the current dev version? Could you please also post a devtools::session_info()?

**Comment by krlmlr** [comment]
Closing for now, please feel free to comment/reopen.
