### ISSUE TITLE
dbConnect fails to read password from ~/.my.cnf 

### ISSUE THREAD

**Issue by stevenpollack** [rstats-db/RMySQL#55]
Here's my (abbreviated) output (I started from a fresh R session):
```R
> devtools::install_github("RcppCore/Rcpp")
[snip]
* DONE (Rcpp)
> devtools::install_github("rstats-db/DBI")
[snip]
* DONE (DBI)
> devtools::install_github("rstats-db/RMySQL")
[snip]
* DONE (RMySQL)
> library(DBI)
> X <- dbConnect(RMySQL::MySQL(), groups="rs-dbi")
Error: Failed to connect: Access denied for user 'root'@'localhost' (using password: NO)

Enter a frame number, or 0 to exit

1: dbConnect(RMySQL::MySQL(), groups = "rs-dbi")
2: .valueClassTest(standardGeneric("dbConnect"), "DBIConnection", "dbConnect")
3: is(object, Cl)
4: is(object, Cl)
5: .local(drv, ...)
6: connection_create(host, username, password, dbname, port, unix.socket, client.flag, groups, default.file)
```

My `~/.my.cnf` file looks like
```
[rs-dbi]
database=test
user=root
password=alpine
```
And when I try and access `mysql` via CLI:
```
$ mysql --user=root --password=alpine test
ERROR 1049 (42000): Unknown database 'test'
```

**Comment by hadley** [comment]
This is with the dev version, right?

**Comment by hadley** [comment]
This is with the dev version, right?

**Comment by hadley** [comment]
This is with the dev version, right?

**Comment by stevenpollack** [comment]
This is following the instructions in the README, which installs from the master branch. I presume if I'm installing from this repo, I'm taking the dev version, eh?

**Comment by hadley** [comment]
This is with the dev version, right?

**Comment by pongnguy** [comment]
It looks like RMySQL is not reading from my config file either.  But when I change the name of the file, it throws an error.  Also, I don't pass in a user anywhere else, but somehow it is using one.

**Comment by jeroenooms** [comment]
Does it also not work with the CRAN version?

**Comment by krlmlr** [comment]
There was a change in MySQL 5.6 that [introduces the .mylogin.cnf file](https://dev.mysql.com/doc/refman/5.6/en/option-files.html). Could you please state your MySQL versions and check if adding such a file helps?

**Comment by krlmlr** [comment]
Adding .mylogin.conf (via mysql_config_editor, this is a binary file!) works and is supported on my system. Could you please check if the issue still persists with the most recent dev version?

**Comment by jeroenooms** [comment]
FYI both the windows and osx binary packages now link to [mariadb-connector-c](https://downloads.mariadb.org/connector-c/). Also fedora and ubuntu are now defaulting to the mariadb implementation instead of the legacy mysql client library.

**Comment by krlmlr** [comment]
Thanks. I've seen this. So, development will now continue on the "master" branch?

**Comment by jeroenooms** [comment]
Oh shit, no that is an accident

**Comment by krlmlr** [comment]
Should be fixed now.
