### ISSUE TITLE
Character encoding in dbWriteTable in R

### ISSUE THREAD

**Issue by jghigginson78** [rstats-db/RMySQL#57]
I'm failing to get correct (Japanese) characters when writing a dataframe to MySQL using dbWriteTable. For example if I read the following lines from a CSV file into R, the characters display correctly, but when written to a MySQL table they appear as series of ???. The text lines..

"00043","201411","こんにゃく","おかずその他","普及",2,2
"00043","201411","こんにゃく","おかずその他","通年",1,1
"00043","201411","こんにゃく","その他こんにゃく","-",1,1
"00043","201411","こんにゃく","つき白滝","中質",4,3
"00043","201411","こんにゃく","つき白滝","普及",4,1

The R code..

``` R
library(RMySQL)

DF <- read.csv('fpo.csv', stringsAsFactors=FALSE)
dbase <- 'wnp_2_3_new'
con <- dbConnect(MySQL(), user='root', password=pw, dbname=dbase)
rs <- dbGetQuery(con, 'set character set utf8')
dbWriteTable(con, 'fpo_out', overwrite=TRUE, DF)
dbDisconnect(con)
```

**Comment by hadley** [comment]
Rather than using a csv, could you please include `dput(DF)`?  And I'll also need the results of  `Sys.getlocale()`

**Comment by jghigginson78** [comment]
Here’s the result of sys.getlocale(), and the dput(DF) is attached.

[1] "en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8”


> On Mar 13, 2015, at 20:02, Hadley Wickham <notifications@github.com> wrote:
> 
> Rather than using a csv, could you please include dput(DF)? And I'll also need the results of Sys.getlocale()
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/rstats-db/RMySQL/issues/57#issuecomment-78919372>.
> 


structure(list(Store_code = c(43L, 43L, 43L, 43L, 43L, 43L, 43L, 
43L, 43L, 43L, 43L, 43L, 43L, 43L, 43L, 43L, 43L, 43L, 43L, 43L
), Pos_month = c(201411L, 201411L, 201411L, 201411L, 201411L, 
201411L, 201411L, 201411L, 201411L, 201411L, 201411L, 201411L, 
201411L, 201411L, 201411L, 201411L, 201411L, 201411L, 201411L, 
201411L), Prod_category = c("こんにゃく", "こんにゃく", 
"こんにゃく", "こんにゃく", "こんにゃく", "こんにゃく", 
"こんにゃく", "こんにゃく", "こんにゃく", "こんにゃく", 
"こんにゃく", "こんにゃく", "こんにゃく", "こんにゃく", 
"佃煮惣菜", "佃煮惣菜", "佃煮惣菜", "佃煮惣菜", 
"佃煮惣菜", "佃煮惣菜"), Prod_subcategory = c("おかずその他", 
"おかずその他", "その他こんにゃく", "つき白滝", 
"つき白滝", "デザート", "他形状", "他形状", "小結白滝", 
"小結白滝", "涼味おかず", "甘味", "角こん", "角こん", 
"その他佃煮", "佃煮こんぶ", "佃煮惣菜その他", 
"佃煮豆", "佃煮魚介", "惣菜"), Prod_grade = c("普及", 
"通年", "-", "中質", "普及", "通年", "中質", "普及", 
"上質", "普及", "通年", "通年", "中質", "普及", "-", 
"-", "-", "-", "-", "-"), Tot_items = c(2L, 1L, 1L, 4L, 4L, 2L, 
2L, 2L, 1L, 1L, 1L, 1L, 2L, 3L, 1L, 10L, 1L, 8L, 7L, 15L), Num_items = c(2L, 
1L, 1L, 3L, 1L, 2L, 2L, 2L, 1L, 1L, 1L, 1L, 2L, 1L, 1L, 3L, 1L, 
2L, 3L, 0L)), .Names = c("Store_code", "Pos_month", "Prod_category", 
"Prod_subcategory", "Prod_grade", "Tot_items", "Num_items"), class = "data.frame", row.names = c(NA, 
-20L))

**Comment by hadley** [comment]
This works for me:

```R
con <- dbConnect(MySQL())

df <- data.frame(x = 1, y = "佃煮惣菜")
dbWriteTable(con, 'test-utf8', df, temporary = TRUE)
dbReadTable(con, 'test-utf8')

dbDisconnect(con)
```

**Comment by jghigginson78** [comment]
It must be something in my set-up then. If I try the same lines, I get a warning on dbWriteTable

Warning message:
In result_create(conn@ptr, statement) : Cancelling previous query

and the session aborts on the dbReadTable

**Comment by hadley** [comment]
(I see the warning too - it's on my list to fix) Are you on linux?

**Comment by jghigginson78** [comment]
Mac Yosemite

**Comment by jghigginson78** [comment]
I don’t know if it is relevant but the pre-rewrite version of dbWriteTable worked for me, at least in terms of writing recognisable Japanese characters to the database

**Comment by jghigginson78** [comment]
Just to close this off. It is working fine now with the development version of RMySQL. I ended up re-installing MySQL and sorting out a problem with collations in my database (which Tableau objected to). Thanks you for your help - and for all the other great development you have done (in dplyr etc).

**Comment by vaidyasm** [comment]
Hello Hadley, 
I'm also having issue with inserting unicode characters.

Here are the outputs from some of your commands mentioned above:
```
> Sys.getlocale()
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"

> x <- "佃煮惣菜"
> x
[1] "佃煮惣菜"
> dput(x)
"<U+4F43><U+716E><U+60E3><U+83DC>"
> Encoding(x)
[1] "UTF-8"


> con <- dbConnect(MySQL())

> df <- data.frame(x = 1, y = "佃煮惣菜")
> dput(df)
structure(list(x = 1, y = structure(1L, .Label = "<U+4F43><U+716E><U+60E3><U+83DC>", class = "factor")), .Names = c("x", 
"y"), row.names = c(NA, -1L), class = "data.frame") 


> dbWriteTable(con, 'test_utf8', df, temporary = FALSE)
> dbReadTable(con, 'test_utf8')
  x                                y
1 1 <U+4F43><U+716E><U+60E3><U+83DC>
```

Mysql Workbench also reports
```
<U+4F43><U+716E><U+60E3><U+83DC>
```
for y.


```
SHOW CREATE TABLE test_utf8
```
results in
```
CREATE TABLE `test_utf8` (
	`row_names` TEXT NULL COLLATE 'utf8_unicode_ci',
	`x` DOUBLE NULL DEFAULT NULL,
	`y` TEXT NULL COLLATE 'utf8_unicode_ci'
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB
;
```


```
DBI::dbGetQuery(con, "show variables like 'character_set_%'")
```
results in
```
             Variable_name                                        Value
1     character_set_client                                         utf8
2 character_set_connection                                         utf8
3   character_set_database                                         utf8
4 character_set_filesystem                                       binary
5    character_set_results                                         utf8
6     character_set_server                                         utf8
7     character_set_system                                         utf8
8       character_sets_dir C:\\bin\\mysql-server-5.5\\share\\charsets\\
```



I'm also having issue retrieving unicode characters.
On the table test_utf8 table, I inserted a row with row.names = 2, x = 2, and y = "OôEé" via Mysql Workbench.

```
> dbReadTable(con, 'test_utf8')
  x                                y
1 1 <U+4F43><U+716E><U+60E3><U+83DC>
2 2                           OÃ´EÃ©
```


In my.ini, I have
```
character-set-server=utf8
collation=utf8_unicode_ci
skip-character-set-client-handshake
```

Could you help me with pin-pointing the issue?

Thanks in advance.

**Comment by krlmlr** [comment]
Related: #93.

**Comment by valentas-kurauskas** [comment]
I also thought I had this issue, but it turned out this was because my MySQL database had the default latin1 charset. The [following query](https://stackoverflow.com/a/23815688/2361465) fixes this:

    ALTER DATABASE databasename CHARACTER SET utf8 COLLATE utf8_general_ci;

**Comment by sanjmeh** [comment]
@valentas-kurauskas : I am going to run the above command on my database (of course taking a backup of it before that). Will it solve the problem of R unable to write to the MySQL DB using INSERT - VALUES.  This happens when R outputs a character vector with single quotes (sQoute)?

**Comment by sanjmeh** [comment]
Nopes. MySQL database is already on utf8_general_ci; 
How to make sure R outputs the strings into the same character set. Here's a sample code that is rejected in MySQL on Ubuntu (running on AWS) with a character set problem. I strongly suspect it is not liking the single quotes used by R.

` sql_text<-paste("INSERT (CLASS, DATE) VALUE (10", sQuote(now())
n<-dbExecute(db,sql_text)
`
The error I get is:

> Error in .local(conn, statement, ...) : could not run statement: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '��2017-06-13 04:28:10’

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
