### ISSUE TITLE
dates as posixct in case statements with else clauses

### ISSUE THREAD

**Issue by natecobb** [rstats-db/RMySQL#58]
I've getting weird behavior with dates in CASE statements - perhaps it is MySQL but its seems to be the driver and is new since the 0.9.x branch. In certain cases when I return a date from a CASE statement the date is coerced to posix and mangled. It seems to occur if there is an ELSE clause in the CASE, but can't make any sense of why this would occur. (Just tested with a fresh pull of the master branch). I initially ran into this returning date fields from a table, but this reproduces the problem:

```
x = dbSendQuery(source_conn, "select date('1968-10-22') as foo, 
      (case when TRUE then  date('1968-10-22') else NULL end) as biff, 
      (case when TRUE then date('1968-10-22') end) as bap, 
      (case when TRUE then date('1968-10-22') else date('1968-10-23') end) as baz;")
dbColumnInfo(x)
```

```
  name    type
1  foo    Date
2 biff POSIXct
3  bap    Date
4  baz POSIXct
```

```
dbFetch(x)
```

```
         foo              biff        bap               baz
1 1968-10-22 -1-11-30 00:20:08 1968-10-22 -1-11-30 00:20:08
```

directly from MySQL

```
mysql> select date('1968-10-22') as foo, 
          (case when TRUE then  date('1968-10-22') else NULL end) as biff, 
          (case when TRUE then date('1968-10-22') end) as bap, 
          (case when TRUE then date('1968-10-22') else date('1968-10-23') end) as baz;
+------------+------------+------------+------------+
| foo        | biff       | bap        | baz        |
+------------+------------+------------+------------+
| 1968-10-22 | 1968-10-22 | 1968-10-22 | 1968-10-22 |
+------------+------------+------------+------------+
1 rows in set (0.03 sec)

mysql> 
```

**Comment by krlmlr** [comment]
Thanks. Do you still see this behavior with the current dev version? Could you please also post a devtools::session_info()?

**Comment by krlmlr** [comment]
Closing for now, please feel free to comment/reopen.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
