### ISSUE TITLE
RMySql error today

### ISSUE THREAD

**Issue by songyurita** [rstats-db/RMySQL#59]
I was still working today at noon, now it throw out this error:
Error in as.integer(from) : 
  cannot coerce type 'S4' to vector of type 'integer'

**Comment by jeroenooms** [comment]
Did you load RPostgreSQL?

**Comment by songyurita** [comment]
@jeroenooms yes, I need both mysql and posgres

**Comment by jeroenooms** [comment]
Duplicate @ https://github.com/rstats-db/RMySQL/issues/46.

**Comment by jeroenooms** [comment]
You should be able to use both, I think the error only pops up when you `print()` the connection. Alternatively you can switch to the dev version of rmysql which does not have this problem.

**Comment by songyurita** [comment]
Thanks, this is fixed by restarting Rstudio and install dev version of rmysql.
