### ISSUE TITLE
dbWriteTable and character sets

### ISSUE THREAD

**Issue by gagern** [rstats-db/RMySQL#6]
Since dbWriteTable passes its data through a temporary file, the character set used for writing depends on the current locale of the R session, whereas the one used for reading depends on the MySQL configuration. These two do not neccessarily agree.

Quoting from [the docs](https://dev.mysql.com/doc/refman/5.1/en/load-data.html):

>  `SET NAMES` and the setting of `character_set_client` do not affect interpretation of input.

It would be nice if R could write that data with a specific, well-defined and sufficiently universal character set, probably UTF-8, and also include a matching `CHARACTER SET` clause to the `LOAD DATA LOCAL INFILE` command passed to the server.

As an alternative, one could of course consider loading data without a temporary file, using a prepared insert statement instead. Doing so would likely solve this issue here as well as issue #1.

**Comment by hadley** [comment]
In the dev version, this now works

```R
con <- mysqlDefault()
df <- data.frame(foo=c("Simple ASCII", "Unicode T\u{00eb}st", "More ASCII"))

dbWriteTable(con, "test", df)
dbReadTable(con, "test")
#>            foo
#> 1 Simple ASCII
#> 2 Unicode Tëst
#> 3   More ASCII
```

**Comment by jeroenooms** [comment]
We should add some unit tests for UTF8 examples as this is likely to cause problems with Rcpp and/or windows.

**Comment by hadley** [comment]
I do have a couple in there already

**Comment by gagern** [comment]
It seems you had a few busy days. Some great changes, as far as I can tell from the sources. The custom `mysqlWriteTable` is gone, isn't it? That will break backwards compatibility. Would it make sense to provide an alias for this? Perhaps along with a deprecation warning, so that people can move code to `dbWriteTable` in a graceful way without current stuff failing on them? I might be misreading the sources, though, since I can't actually test them due to #47. And I certainly don't fully understand the relevant part of the code, since the code looks as if you only supported writing content from a file, while the examples here use an in-memory data frame. I guess it's some DBI infrastructure which is writing that to a file, but if that is the case, could we somehow get that function to pass the data frame along, so we don't have to re-read the file-based table?

**Comment by hadley** [comment]
`mysqlWrite` was deprecated in the previous release.

`dbWriteTable()` writes directly from memory if you give it a data frame - make sure you're looking at the first method
