### ISSUE TITLE
support emoji (utf8mb4)

### ISSUE THREAD

**Issue by graingert** [rstats-db/RMySQL#60]
From the [sqlalchemy docs](http://docs.sqlalchemy.org/en/latest/dialects/mysql.html):

> The encoding used for Unicode has traditionally been 'utf8'. However, for MySQL versions 5.5.3 on forward, a new MySQL-specific encoding 'utf8mb4' has been introduced. The rationale for this new encoding is due to the fact that MySQL’s utf-8 encoding only supports codepoints up to three bytes instead of four. Therefore, when communicating with a MySQL database that includes codepoints more than three bytes in size, this new charset is preferred, if supported by both the database as well as the client DBAPI

**Comment by hadley** [comment]
So utf8mb4 is "real" utf-8?

**Comment by graingert** [comment]
Yeah it's utf8mb4 is UTF-8 as described by https://tools.ietf.org/html/rfc3629

The original description of UTF-8 allowed for up to 6-byte characters

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
