### ISSUE TITLE
duplication of data

### ISSUE THREAD

**Issue by mblaauw** [rstats-db/RMySQL#65]
DBI 0.3.1.9008
RMySQL 0.11.0.9000
Ubuntu 14.04
mysql  Ver 14.14 Distrib 5.6.19, for debian-linux-gnu (x86_64) using  EditLine wrapper

Problem: duplication of data with both dbGetQuery(con, "SELECT * FROM TABLE") and dbReadTable("TABLE")

Problem: 

Result of "select * from table" from MySQL ->
```
id | name | value
---------------------------
1 | test | 10
---------------------------
2 | NULL  | NULL      
---------------------------
```
Result of same query from RMySQL (dbGetQuery and dbReadTable)
```
id | name | value
---------------------------
1 | test | 10
---------------------------
2 | test  | 10     
---------------------------
```
So EMPTY or NULL values get overwritten by the previous value.

**Comment by hadley** [comment]
Would you mind making this into a minimal reproducible example? (i.e. something I can copy and paste into R) That saves me some time when debugging it.  Also you can surround code in ```` ``` ```` so it displays correctly.

**Comment by mblaauw** [comment]
Sure! Thanks for looking into it in the first place. Don't waste to much time on this as I start to suspect driver or MySQL install/config. Weird issue though. 

```
library('DBI')
library('RMySQL')

# create connection
con <- dbConnect(drv = MySQL(), user = 'import', dbname="datahub")

# Read data and output the result to see original structure
test_data <- read.csv('data/test.csv', sep = ',') 
test_data

# write df to MySQL
if (dbExistsTable(con,'test') == T) {
  dbGetQuery(con, "DROP TABLE test;")
  dbWriteTable(con, value = test_data,  name = "test")
} else {
  dbWriteTable(con, value = test_data,  name = "test")
}

# output the result 
dbReadTable(con, "test")

# close
dbDisconnect(con)
```

and here is the input file;

```
"key","value"
1,""
2,"Hello"
56,""
254,""
258,"Wagemans"
259,""
260,"Droog"
262,"Königs"
264,""
```

The final (clearly wrong) output of the code:

```
  key    value
1   1         
2   2    Hello
3  56    Hello
4 254    Hello
5 258 Wagemans
6 259 Wagemans
7 260    Droog
8 262   Königs
9 264   Königs
```

Thanks again for looking into this!

**Comment by hadley** [comment]
I'm pretty sure it's my fault (I can picture exactly where the problem is).  Would you mind making the example slightly more self-contained to inline the data set? i.e. create it with `data.frame(key = ..., value = ...)`

**Comment by mblaauw** [comment]
Yep, no problem. Here it is (if I understood you right):

```
library('DBI')
library('RMySQL')

# create connection
con <- dbConnect(drv = MySQL(), user = 'import', dbname="datahub")

# create the dataset & output the result to verify
keys <- c('1', '2','3','4')
names <- c('Hadley', '','Michel','')

test_data <- data.frame(key = keys, name = names)
test_data


# write df to MySQL
if (dbExistsTable(con,'test') == T) {
  dbGetQuery(con, "DROP TABLE test;")
  dbWriteTable(con, value = test_data,  name = "test")
} else {
  dbWriteTable(con, value = test_data,  name = "test")
}

# output the result 
dbReadTable(con, "test")

# close
dbDisconnect(con)
```

test_data outputs:

```
  key   name
1   1 Hadley
2   2       
3   3 Michel
4   4    
```

After the dbReadTable from the MySQL server:

```
  key   name
1   1 Hadley
2   2 Hadley
3   3 Michel
4   4 Michel
```

Again, when check directly on the MySQL, the result is stored correctly. 

Thanks again!

Michel
