### ISSUE TITLE
dbWriteTable ignores field.types param

### ISSUE THREAD

**Issue by pantoniades** [rstats-db/RMySQL#67]
Passing in a list of field types has no effect on dbWriteTable. 

It appears to be that they do not get passed in to the call to DBI::sqlCreateTable on line 92 of table.R

It's a small change, and I am happy to send a pull request. 

thanks

**Comment by pantoniades** [comment]
Sorry, to be more exact it was that in the dbWriteTable(MySQL(), character, data.frame) form it only passes in the df to the sqlCreateTable() call, so column types are determined regardless of what's in the field.types parameter.

**Comment by jlsepulveda** [comment]
Hi pantoniades

I have the same behaviour using dbWriteTable, do you have any update related?

Thanks

**Comment by pantoniades** [comment]
Hi, 

I fixed it in my own branch - see
https://github.com/pantoniades/RMySQL/commit/e3e9f29062e87b8a5ea948e7e51742f478729e3a
for the changed code. 

Philip

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
