### ISSUE TITLE
Error when write table from R

### ISSUE THREAD

**Issue by ywhuofu** [rstats-db/RMySQL#70]
I have a data.frame in R. I tried to write it into MySQL using following commands:
`dbWriteTable(con, name='df', value=df , row.name=F)`
Then I got this error:
`Error: Out of range value for column 'var1' at row 1 [1264]`

I checked, row 1 of `var1` is a NA value. I also did the same using RPostgresql, it worked out smoothly.

**Comment by krlmlr** [comment]
Thanks. Could you please provide a reproducible example?

**Comment by krlmlr** [comment]
Closing for now, please feel free to comment/reopen.
