### ISSUE TITLE
LOAD DATA LOCAL INFILE vs INSERT INTO

### ISSUE THREAD

**Issue by szilard** [rstats-db/RMySQL#71]
For dbWriteTable:
- Latest CRAN version (0.10.3) uses LOAD DATA LOCAL INFILE https://github.com/rstats-db/RMySQL/blob/april/R/table.R#L139
- Latest dev uses INSERT INTO https://github.com/rstats-db/RMySQL/blob/master/R/table.R#L105

Most analytical/columnar/MPP databases (e.g. MySQL-based Infobright) strongly prefer "bulk loads", but my guess is that standard MySQL is faster with LOAD than with INSERT as well http://dev.mysql.com/doc/refman/5.0/en/insert-speed.html

Also, the latest dev uses one INSERT per row rather then "bulk insert" (not to be confused with "bulk load") http://stackoverflow.com/questions/7977172/mysql-multiple-insert-performance Looping 1 row at a time is probably the slowest solution.

Any comments @jeroenooms @hadley on why LOAD was changed to INSERT?

PS: The way I found this is that the latest CRAN 0.10.3 does not work with Infobright (call it a "bug") as Infobright has different FIELDS TERMINATED BY defaults. Adding `FIELDS TERMINATED BY '\t'` here https://github.com/rstats-db/RMySQL/blob/april/R/table.R#L141 would fix the issue on 0.10.3, but that's moot in dev (as LOAD was changed to INSERT).

**Comment by jeroenooms** [comment]
We can still do more maintenance releases in the 10.x (stable) branch. Can you submit a PR for the [stable](https://github.com/rstats-db/RMySQL/tree/stable) branch with the fix?

**Comment by szilard** [comment]
submitted PR (the brach is named "april" not "stable", right?)

**Comment by jeroenooms** [comment]
Thanks. Either one will do. Can you add a bullet to the `NEWS.md` file ?

**Comment by szilard** [comment]
done

**Comment by jeroenooms** [comment]
Ok merged. FYI I renamed the `april` branch to `stable`.

**Comment by szilard** [comment]
So, this fix above affected only the minor bug in some MySQL based systems (Infobright) in the stable branch. 

The original question of changing `LOAD DATA` to `INSERT` in the dev version still remains. @jeroenooms @hadley I just tested it, the dev version is 100x slower in inserting data from R to MySQL (stable: 1mil rows 11sec, dev: 10K rows 11sec: https://github.com/szilard/benchm-R-mysql )

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
