### ISSUE TITLE
the append of dbWriteTable  does not work

### ISSUE THREAD

**Issue by WonderDream** [rstats-db/RMySQL#76]
The append option of the dbWriteTable seems not to work correctly.
When I tried to append the data to the existed table with the append=T option, I got a failure.

The code is below:
if(dbExistsTable(conn, 'mytable')) {
     dbWriteTable(conn, 'mytable', data, row.names = F, append = T, overwrite = F)
 } else {
       dbWriteTable(conn, 'mytable', data, row.names = F)
}

**Comment by hadley** [comment]
Please provide a minimal reproducible example

**Comment by WonderDream** [comment]
I can't reproduce this trouble any more. I don't know why, but it did give me the error message that the table already existed in the last few tries. I hope I will never encounter this problem again. Thanks all the same.
