### ISSUE TITLE
No way to fetch large integers

### ISSUE THREAD

**Issue by sambrightman** [rstats-db/RMySQL#77]
As far as I can tell it's not possible to fetch e.g. bigint(20) columns without losing data. Is it possible for RMySQL to provide an option to do the least worst thing and internally switch to doubles for large integer columns? I also int64 and bit64 packages that could be used?

**Comment by sambrightman** [comment]
I made local changes as per 9c950629f311f805ccb87b409b1654ec7e57af9f and so far it seems to help.

**Comment by hadley** [comment]
I think that's a reasonable starting place, but you do need to check for int64 values that are outside the bounds of a double

**Comment by sambrightman** [comment]
Agreed; it would be better to use a full 64-bit integer implementation. Doesn't that problem already exist though?

**Comment by hadley** [comment]
Yeah, there's not an easy way to fix that in R until we get a native 64-bit int type. int64/bit64 work by putting an int64 into a double and then adding a whole bunch of S3 methods. The problem is that if you don't override the right method, or the class attribute is lost, you'll silently get incorrect results.

**Comment by sambrightman** [comment]
So would it be feasible to actually accept something like this? The existing implementation gets incorrect results for a smaller range, right?

**Comment by hadley** [comment]
Yeah, it should be fine. It's not perfect, but it's better than the current behaviour.  But I'm not actively working on the db backends at the moment, and I'll probably tackle int64 consistently across them all at one time, at some point in the future.

**Comment by krlmlr** [comment]
Probably the safest option here would be return a character vector here, and let the user figure out what to do with the data.

**Comment by hans-ekbrand** [comment]
This is a PITA when storing twitter ids in mysql and then retrieving them with RMySQL.

Unexpectedly, RMySQL mangles data and returns `numeric` even when the column definition is `varchar(20)`, if only the contents is all numbers. I consider this behaviour a bug. I had to resort to using `system()`. e.g.

`system(command="mysql --skip-column-names --batch  -e \"select id from tweets\"", intern=TRUE)`

Which is exactly what you want to avoid and the reason to use RMySQL.

**Comment by krlmlr** [comment]
@hans-ekbrand: I can't replicate what you describe: When I create a table with a varchar(20) column, the data is returned as character. (Note that this is for the dev version, which requires both DBI and RMySQL from GitHub.) The same should happen if you use [coercion](http://dev.mysql.com/doc/refman/5.7/en/cast-functions.html) in a query. Please post a reproducible example if this does not work for you.

**Comment by daroczig** [comment]
Just to provide a minimal reproducible example with dev version: `SELECT 1234567890123456789` returns `2112454933` in R.

**Comment by krlmlr** [comment]
Moved to rstats-db/RMariaDB (see link above).
