### ISSUE TITLE
Instrictions for anormal installation

### ISSUE THREAD

**Issue by Holzhauer** [rstats-db/RMySQL#80]
A few instructions on how to install RMySQL in non-standard environments, e.g. if one is not able to install MySQL client because of missing admin rights, would be helpful, as instructions for previous versions (0.9-3) do not work anyore (e.g. setting  PKG_CPPFLAGS and PKG_LIBS directly).
For me, it was sufficient to set MYSQL_DIR (not MYSQL_HOME as one would expect) to the MySQL client directory which includes 'include' and 'lib', and to copy libmysqlclient.so.18 to R's lib folder.

**Comment by krlmlr** [comment]
Do the comments in #99 help with this issue?

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
