### ISSUE TITLE
dbWriteTable not works properly

### ISSUE THREAD

**Issue by ceste** [rstats-db/RMySQL#81]
Hi, 

I tried to insert my data frame to certain table that already exist but with empty records. First time I try to load it to table using this script : 

dbWriteTable(conn=con,name='standard_report',value=as.data.frame(df),  append = TRUE, row.names = F)

It works properly but second time I tried with different data frame it not works though I got "TRUE" message after I run the same script. 

Next, I try to delete all records and tried to do the same thing, it only insert one row to my table. 

How can I fix this?

Please advice

**Comment by hadley** [comment]
Please provide a minimal reproducible example

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
