### ISSUE TITLE
dbWriteTable append throws error on attempt to append df to existing table. 

### ISSUE THREAD

**Issue by mackenna** [rstats-db/RMySQL#82]
The following is a function that I use to append a data frame 

library("DBI")
library("RMySQL")

appendSpreadsToDatabaseTable <- function( spreaddataframe )
{

  pgdrv <- dbDriver("MySQL")
  dwconnection <- dbConnect(pgdrv, "dwdatabase", username="dam", password="njhg77676");
  dbWriteTable(conn = dwconnection, value = spreaddataframe, name = "spreads" , row.names = F , append = T , overwrite = F  ) 
  dbDisconnect(dwconnection)
  return() 
  
}

I call this function the first time and it creates a new table called spreads with the data appropriately.   

appendSpreadsToDatabaseTable( spreadsdf1 )
 

When I call the same function a second time with a separate dataframe of the same format, as follows 

appendSpreadsToDatabaseTable( spreadsdf1 )

I anticipate spreadsdf2  is appended to the spreads table as I specify append = T and spreads now contains spreaddf1 + spreaddf2.

The first time around it creates the table just fine.

The second time I call this function ( in a loop ) it throws an error indicating 

Error in .local(conn, statement, ...) : 
  could not run statement: Table 'spreads' already exists

I have had this working in a previous version and now the append does not seem to work anymore.

I have also tried adding overwrite = F   explicitly with no success.

package version of RMySQL is 

> packageVersion("RMySQL")
[1] ‘0.10.3’

any pointers

**Comment by mackenna** [comment]
Looks like it is similar to # 76   which has been closed.

**Comment by MCCCLXXXV** [comment]
This problem happens to me when I call dbWriteTable with the table name specified in all caps.  
For example, I was calling:
dbWriteTable(con,"K_WDGQRSHP",keydatadf,row.names=T,append=T) 
and getting the error:
could not run statement: Table 'k_wdgqrshp' already exists
but calling this worked just fine:
dbWriteTable(con,"k_wdgqrshp",keydatadf,row.names=T,append=T)

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen. A minimal reproducible example would be great.

**Comment by nicolerobledo** [comment]
I also encountered this problem, I just used **small letters for my table name .**.. hope it would work. God Bless

**Comment by lomiarzpraca** [comment]
i don't have any capital letters in table name and still get this error :/
