### ISSUE TITLE
Error RS_MySQL_cloneConnection 

### ISSUE THREAD

**Issue by irismiliaraki** [rstats-db/RMySQL#92]
I get this error and the connection to the database fails:

`Error RS_MySQL_cloneConnection in package /usr/local/lib/R/site-library/RMySQL/libs/RMySQL.so` 

I cannot track really when and why it happens since this occurs occasionally without obvious reason.
Almost nothing appears after searching.

**Comment by krlmlr** [comment]
Which OS are you on, which versions of R and RMySQL are you using? Could you please post the R stack trace?

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
