### ISSUE TITLE
SSL Connection on OSX

### ISSUE THREAD

**Issue by barnettjacob** [rstats-db/RMySQL#96]
Hi. Although it has worked in the past I've developed an issue where I am unable to connect to SSL protected databases on my Mac. I can happily connect using other tools such as mysql workbench etc.

I get this error:

`Failed to connect to database: Error: Access denied for user 'xxxxxxx'@'xx.xx.xxx.xx' (using password: YES)`

My connection string looks like this:

```test <- dbConnect(RMySQL::MySQL(),
          host='xxxxxxxxx',
          username='xxxxxx',
          password='xxxxxxxxx',
          dbname='xxxxxxxx',
          default.file='/Users/jb/condoc.txt')```

Where the contents of condoc.txt is: 
```[client] ssl-ca = /Users/jb/rds-ca-2015-eu-west-1.pem```

My linux machine works fine although I'm on an older version of the package (9.3), rolling back to this version on Mac didn't help. 

I've tried different versions of the connection string format including the `.my.cfg` approach in the readme which yields the same result. 

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11 (El Capitan)

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RMySQL_0.10.6 DBI_0.3.1    

loaded via a namespace (and not attached):
[1] tools_3.2.2   Rcpp_0.12.1.2```

**Comment by jeroenooms** [comment]
Can you connect with the same parameters from the command line mysql client?

**Comment by jeroenooms** [comment]
Also inspect the log files on the server to see if there is a hint on why it is denying access.

**Comment by barnettjacob** [comment]
Thanks will try this.

**Comment by barnettjacob** [comment]
Just to confirm that we got this going eventually. Wasn't the package itself but a problem with where it was installed - we uninstalled and put in the right place and it fixed the problem. Thanks again.

**Comment by funnng** [comment]
got the same issue with dev version of RMySQL, works well with using host/username/password/dbname, but fail with using .my.cnf

**Comment by krlmlr** [comment]
@funnng: Could you please open a new issue that includes your session_info() and a brief description?

**Comment by funnng** [comment]
@krlmlr   #120 is the new issue.
