### ISSUE TITLE
dbConnect crashes when using 'localhost' or '127.0.0.1' as host

### ISSUE THREAD

**Issue by ahmeier** [rstats-db/RMySQL#97]
I have tried to connect to a MySQL server using the RMySQL package utilizing an ssh tunnel. Using this command:
````
mydb<-dbConnect(MySQL(),user='xxxx',password='yyyy',host='localhost',db='zzzz')
````
 I get a program crash for R that requires a shutdown of the program. This is a real issue as my work IT department is extremely restrictive and blocks the outgoing 3306 port. I have an ssh tunnel to the remote MySQL server which allows me to connect to mysql from the command line, but can't pull data into R due to this issue.

The error message is:
````
*** caught illegal operation ***
address 0x1081f0569, cause 'illegal opcode'

Traceback:
 1: .Call(RS_MySQL_newConnection, drv@Id, dbname, username, password,     host, unix.socket, as.integer(port), as.integer(client.flag),     groups, default.file[1])
 2: .local(drv, ...)
 3: dbConnect(MySQL(), user = "xxxx", password = "yyyy", host = "localhost",     db = "zzzz")
 4: dbConnect(MySQL(), user = "xxxx", password = "yyyy", host = "localhost",     db = "zzzz")
````

Looking through some older posts online it appears that this problem has occurred before
I am on a MacPro 1,1 running the most recent R and RMySQL packages

**Comment by krlmlr** [comment]
This works for me on Ubuntu. Which version of RMySQL are you using?

**Comment by krlmlr** [comment]
Closing for now, please feel free to reopen.
