### ISSUE TITLE
dbListConnections appears to not be present in GitHub (non-CRAN) version: is this an issue?

### ISSUE THREAD

**Issue by sopko16** [rstats-db/RMySQL#98]
Hello,

Apologies if I have overlooked something basic. I am trying to run this code:

db <- RMySQL::MySQL()
dbListConnections(db)
from page 10 of this documentation: https://cran.r-project.org/web/packages/RMySQL/RMySQL.pdf

It looks like this GitHub version is different from the CRAN version. Basically, on GitHub, I believe this has just been changed with MySQL() to only ever allow one connection (while it does allow more than one on CRAN package). 

1.) Has this been changed in this way on GitHub like I suspect?
2.) Since I cannot list all connections (to then be able to close any open ones that I might not have closed), is it the case that I now do not need to worry about this?- That there is only one connection allowed open at a time and I do not need to worry about managing/closing them?

I ask because using CRAN I would occasionally get a message about having a 16 connection max open and I would then need to run:
all_cons <- dbListConnections(MySQL())
for(con in all_cons){dbDisconnect(con)}

and I want to be sure this is the case prior to adopting this code; It looks this way from my testing, but I still wanted to confirm here if possible.

Thanks,
Mike

**Comment by hadley** [comment]
Connections are now automatically disconnected when they're gc'd. Provided that they go out of scope, you shouldn't need to worry about manually cleaning up.
